In [1]:
import numpy as np

In [2]:
data = ['my data',
        'my name is ihtisham',
        'my father name is RahmanAli', 
        'my brother name is imad',
        'my age is 24'
       ]

# Step-1 Generate Indexes

In [3]:
from keras.preprocessing.text import Tokenizer

In [4]:
tokenizer = Tokenizer(oov_token='')

In [5]:
tokenizer.fit_on_texts(data)

In [6]:
tokenizer.word_index

{'': 1,
 'my': 2,
 'is': 3,
 'name': 4,
 'data': 5,
 'ihtisham': 6,
 'father': 7,
 'rahmanali': 8,
 'brother': 9,
 'imad': 10,
 'age': 11,
 '24': 12}

In [7]:
tokenizer.word_counts

OrderedDict([('my', 5),
             ('data', 1),
             ('name', 3),
             ('is', 4),
             ('ihtisham', 1),
             ('father', 1),
             ('rahmanali', 1),
             ('brother', 1),
             ('imad', 1),
             ('age', 1),
             ('24', 1)])

In [8]:
tokenizer.document_count

5

# Step-2 Make Sequences of words in Sentences

In [9]:
sequences = tokenizer.texts_to_sequences(data)

In [10]:
sequences

[[2, 5], [2, 4, 3, 6], [2, 7, 4, 3, 8], [2, 9, 4, 3, 10], [2, 11, 3, 12]]

In [11]:
tokenizer.index_word

{1: '',
 2: 'my',
 3: 'is',
 4: 'name',
 5: 'data',
 6: 'ihtisham',
 7: 'father',
 8: 'rahmanali',
 9: 'brother',
 10: 'imad',
 11: 'age',
 12: '24'}

# Step-3 Apply Padding To make the Sequences of Same Sizes

In [12]:
from keras.utils import pad_sequences

In [13]:
sequences = pad_sequences(sequences=sequences, padding='post')

In [14]:
sequences

array([[ 2,  5,  0,  0,  0],
       [ 2,  4,  3,  6,  0],
       [ 2,  7,  4,  3,  8],
       [ 2,  9,  4,  3, 10],
       [ 2, 11,  3, 12,  0]])

In [15]:
# it added 0's at the end to make the squences of same sizes

 ____________________________

 ____________________________

# Project on IMDB Reviews

In [16]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [17]:
# (x_train, y_train),(x_test, y_test) = imdb.load_data()

In [18]:
import numpy as np

imdb = np.load('C:/Users/92314/Desktop/Ehunar/Neural Network/RNN/imdb.npz', allow_pickle=True)
lst = imdb.files


In [19]:
lst

['x_test', 'x_train', 'y_train', 'y_test']

In [20]:
x_train = imdb['x_train']
y_train = imdb['y_train']
x_test = imdb['x_test']
y_test = imdb['y_test']

In [21]:
x_train

array([list([23022, 309, 6, 3, 1069, 209, 9, 2175, 30, 1, 169, 55, 14, 46, 82, 5869, 41, 393, 110, 138, 14, 5359, 58, 4477, 150, 8, 1, 5032, 5948, 482, 69, 5, 261, 12, 23022, 73935, 2003, 6, 73, 2436, 5, 632, 71, 6, 5359, 1, 25279, 5, 2004, 10471, 1, 5941, 1534, 34, 67, 64, 205, 140, 65, 1232, 63526, 21145, 1, 49265, 4, 1, 223, 901, 29, 3024, 69, 4, 1, 5863, 10, 694, 2, 65, 1534, 51, 10, 216, 1, 387, 8, 60, 3, 1472, 3724, 802, 5, 3521, 177, 1, 393, 10, 1238, 14030, 30, 309, 3, 353, 344, 2989, 143, 130, 5, 7804, 28, 4, 126, 5359, 1472, 2375, 5, 23022, 309, 10, 532, 12, 108, 1470, 4, 58, 556, 101, 12, 23022, 309, 6, 227, 4187, 48, 3, 2237, 12, 9, 215]),
       list([23777, 39, 81226, 14, 739, 20387, 3428, 44, 74, 32, 1831, 15, 150, 18, 112, 3, 1344, 5, 336, 145, 20, 1, 887, 12, 68, 277, 1189, 403, 34, 119, 282, 36, 167, 5, 393, 154, 39, 2299, 15, 1, 548, 88, 81, 101, 4, 1, 3273, 14, 40, 3, 413, 1200, 134, 8208, 41, 180, 138, 14, 3086, 1, 322, 20, 4930, 28948, 359, 5, 3112, 2128, 1, 20045

In [22]:
y_train

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [23]:
x_train.shape

(25000,)

In [24]:
y_train.shape

(25000,)

In [25]:
x_train[0]

[23022,
 309,
 6,
 3,
 1069,
 209,
 9,
 2175,
 30,
 1,
 169,
 55,
 14,
 46,
 82,
 5869,
 41,
 393,
 110,
 138,
 14,
 5359,
 58,
 4477,
 150,
 8,
 1,
 5032,
 5948,
 482,
 69,
 5,
 261,
 12,
 23022,
 73935,
 2003,
 6,
 73,
 2436,
 5,
 632,
 71,
 6,
 5359,
 1,
 25279,
 5,
 2004,
 10471,
 1,
 5941,
 1534,
 34,
 67,
 64,
 205,
 140,
 65,
 1232,
 63526,
 21145,
 1,
 49265,
 4,
 1,
 223,
 901,
 29,
 3024,
 69,
 4,
 1,
 5863,
 10,
 694,
 2,
 65,
 1534,
 51,
 10,
 216,
 1,
 387,
 8,
 60,
 3,
 1472,
 3724,
 802,
 5,
 3521,
 177,
 1,
 393,
 10,
 1238,
 14030,
 30,
 309,
 3,
 353,
 344,
 2989,
 143,
 130,
 5,
 7804,
 28,
 4,
 126,
 5359,
 1472,
 2375,
 5,
 23022,
 309,
 10,
 532,
 12,
 108,
 1470,
 4,
 58,
 556,
 101,
 12,
 23022,
 309,
 6,
 227,
 4187,
 48,
 3,
 2237,
 12,
 9,
 215]

# Apply Padding

In [26]:
len(x_train[0])

138

In [27]:
len(x_train[1])

433

In [28]:
# as the number of words in reviews are not same, so we need to apply padding

In [29]:
x_train = pad_sequences(x_train, padding='post', maxlen=50) #only pick first 50 words of the reviews
x_test = pad_sequences(x_test, padding='post', maxlen=50) #only pick first 50 words of the reviews

In [30]:
x_train.shape

(25000, 50)

In [31]:
x_train[0]

array([ 3724,   802,     5,  3521,   177,     1,   393,    10,  1238,
       14030,    30,   309,     3,   353,   344,  2989,   143,   130,
           5,  7804,    28,     4,   126,  5359,  1472,  2375,     5,
       23022,   309,    10,   532,    12,   108,  1470,     4,    58,
         556,   101,    12, 23022,   309,     6,   227,  4187,    48,
           3,  2237,    12,     9,   215])

In [32]:
x_train[0].shape

(50,)

In [33]:
x_train[1].shape

(50,)

# Create RNN Model

In [34]:
#as there are 50 words in each review to we will take timesteps=50 so that in every timestep only a single word is passed

<div>
<img src="RNN timesteps.png" width="500" height="400"/>
</div>

In [35]:
model = Sequential()

model.add(SimpleRNN(32, input_shape=(50,1), return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 32)                1088      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 1,121
Trainable params: 1,121
Non-trainable params: 0
_________________________________________________________________


In [36]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [37]:
model.fit(x_train,y_train, epochs=10, validation_data=(x_test,y_test), verbose=2)

Epoch 1/10
782/782 - 13s - loss: 0.6941 - accuracy: 0.5023 - val_loss: 0.6940 - val_accuracy: 0.5018 - 13s/epoch - 17ms/step
Epoch 2/10
782/782 - 10s - loss: 0.6931 - accuracy: 0.5073 - val_loss: 0.6950 - val_accuracy: 0.5080 - 10s/epoch - 13ms/step
Epoch 3/10
782/782 - 8s - loss: 0.6929 - accuracy: 0.5090 - val_loss: 0.6939 - val_accuracy: 0.5080 - 8s/epoch - 11ms/step
Epoch 4/10
782/782 - 8s - loss: 0.6929 - accuracy: 0.5053 - val_loss: 0.6941 - val_accuracy: 0.5001 - 8s/epoch - 11ms/step
Epoch 5/10
782/782 - 9s - loss: 0.6929 - accuracy: 0.5049 - val_loss: 0.6937 - val_accuracy: 0.5027 - 9s/epoch - 11ms/step
Epoch 6/10
782/782 - 8s - loss: 0.6926 - accuracy: 0.5038 - val_loss: 0.6933 - val_accuracy: 0.5070 - 8s/epoch - 11ms/step
Epoch 7/10
782/782 - 9s - loss: 0.6925 - accuracy: 0.5100 - val_loss: 0.6941 - val_accuracy: 0.5089 - 9s/epoch - 11ms/step
Epoch 8/10
782/782 - 8s - loss: 0.6923 - accuracy: 0.5127 - val_loss: 0.6940 - val_accuracy: 0.5048 - 8s/epoch - 11ms/step
Epoch 9/10
7

# What is Embedding?

` Turns positive integers (indexes) into dense vectors of fixed size`

` Dense Vector: most of the values in the vector are non-zero `

` the opposite of Dense-Vector is Sparse-Vector where most of the values in the vector are zero `

<div>
<img src="embedding.jpg" width="500" height="400"/>
</div>

In [38]:
# used to find relation between two similar words

      1) Maps each value in the input array to a vector of defined size
      2) the weights in the layer are learnt during the training process
      3) initialization is perfomed just like other keras layers

## Why use Embedding when we can use OneHotEncoding/ int encoding or Tokenizer?

<div>
<img src="embedding2.png" width="500" height="400"/>
</div>

> `OneHotEncoding is inefficient as most indeces are zero.`
          e.g (Text with 1000 words means most of the elements are 0)
          
> `Integer Encoding does not reflect the relationship between words`

## Where are Embedding Layers Used?

<div>
<img src="embedding3.png" width="600" height="700"/>
</div>

<div>
<img src="embedding4.png" width="600" height="700"/>
</div>

In [39]:
from keras.layers import Embedding

In [40]:
model = Sequential()

In [41]:
model.add(Embedding(10, 50, embeddings_initializer='ones'))

In [42]:
input_array = np.array([0,1,2,3,4,5,6,7,8,9])
output_array = model.predict(input_array)

1/1 [==============================] - 0s 86ms/step


In [43]:
# The 'output_array' will contain the embedded representations for each input index
# It will have the shape (batch_size, sequence_length, output_dim)

In [44]:
output_array.shape #(10,1,50)

(10, 50)

In [45]:
output_array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 

`Here's an example of what each row represents:`

    The first row [1., 1., 1., ...] represents the embedding vector for the input index 0.

    The second row [1., 1., 1., ...] represents the embedding vector for the input index 1.

    This pattern continues for the remaining rows, up to input index 9.

In this specific case, all the embedding vectors are initialized to ones 
because of the 'ones' initializer i used. In practice, the embedding vectors are learned during training 
and are not typically initialized to ones, but this initialization is used here for demonstration purposes. 
During training, the model will adjust these vectors to better represent the relationships between the 
input indices based on the task it's being trained for.







## Text  Preprocessing (word2vec)

<div>
<img src="embedding5.png" width="600" height="700"/>
</div>

In [46]:
data = ['hello how are you feeling',
        'hello how are you doing']

In [47]:
tokenizer = Tokenizer()

In [48]:
tokenizer.fit_on_texts(data)

In [49]:
tokenizer.word_index

{'hello': 1, 'how': 2, 'are': 3, 'you': 4, 'feeling': 5, 'doing': 6}

In [50]:
len(tokenizer.word_index)

6

In [51]:
tokenizer.document_count

2

In [52]:
sequences = tokenizer.texts_to_sequences(data)
sequences

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 6]]

In [53]:
sequences[0]

[1, 2, 3, 4, 5]

In [54]:
sequences[1]

[1, 2, 3, 4, 6]

In [55]:
input_array = np.expand_dims(sequences[1], axis=0)
input_array

array([[1, 2, 3, 4, 6]])

In [56]:
model = Sequential()

model.add(Embedding( 7, output_dim=2, embeddings_initializer='uniform',input_length=5))

output_array = model.predict(input_array)

1/1 [==============================] - 0s 51ms/step


The integers in this array range from 1 to 6. In the context of the Embedding layer, the input_dim parameter specifies the vocabulary size, which should be set to the maximum integer index that appears in your input data.

In the input array [1, 2, 3, 4, 6], the maximum index is 6. 
Therefore, when defining the Embedding layer, you should set input_dim to 7 to account for all possible indices from 0 to 6, inclusive. 
This ensures that the Embedding layer can correctly map all indices to embedding vectors.

In [57]:
output_array

array([[[-0.04415628,  0.00642262],
        [ 0.0264549 , -0.00371405],
        [ 0.04654639, -0.01473019],
        [ 0.01705397,  0.00032941],
        [ 0.00403158,  0.00664105]]], dtype=float32)

In [58]:
output_array.shape

(1, 5, 2)

In [59]:
output_array[0][0] # 1 -> hello

array([-0.04415628,  0.00642262], dtype=float32)

In [60]:
output_array[0][1] # 2 -> how

array([ 0.0264549 , -0.00371405], dtype=float32)

In [61]:
output_array[0][2] # 3 -> are

array([ 0.04654639, -0.01473019], dtype=float32)

In [62]:
output_array[0][3] # 4 -> you

array([0.01705397, 0.00032941], dtype=float32)

In [63]:
output_array[0][4] #6 => doing

array([0.00403158, 0.00664105], dtype=float32)

#  IMDB RNN with Embedding

In [64]:
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras.layers import Dense, SimpleRNN, Embedding, Flatten
from keras import Sequential

In [65]:
x_train = pad_sequences(x_train, padding='post', maxlen=50)
x_test = pad_sequences(x_test, padding='post', maxlen=50)

In [66]:
x_train[0]

array([ 3724,   802,     5,  3521,   177,     1,   393,    10,  1238,
       14030,    30,   309,     3,   353,   344,  2989,   143,   130,
           5,  7804,    28,     4,   126,  5359,  1472,  2375,     5,
       23022,   309,    10,   532,    12,   108,  1470,     4,    58,
         556,   101,    12, 23022,   309,     6,   227,  4187,    48,
           3,  2237,    12,     9,   215])

In [67]:
x_train

array([[ 3724,   802,     5, ...,    12,     9,   215],
       [   20,     1,    82, ...,     5,   336,   406],
       [   24,   106,     6, ...,     6,   176,   397],
       ...,
       [ 1204,     2,    50, ...,    17,    96,    75],
       [ 2489,    35,    75, ..., 51902,  1195,   795],
       [   11,    63,     6, ...,    11,     6,  1347]])

In [68]:
x_train.max()

88582

In [69]:
# Initialize a variable to keep track of the maximum index
max_index = 0

# Iterate through all arrays in the training data
for array in x_train:
    max_in_array = np.max(array)
    max_index = max(max_index, max_in_array)

# Set input_dim to cover all possible indices
input_dim = max_index + 1
input_dim
# Now, you can use input_dim when defining the Embedding layer

88583

In [70]:
model = Sequential()
#            vocablary_size = max + 1
model.add(Embedding( 88583, output_dim=2, embeddings_initializer='uniform',input_length=50))
model.add(SimpleRNN(32, return_sequences=True))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 50, 2)             177166    
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 50, 32)            1120      
                                                                 
 dense_1 (Dense)             (None, 50, 1)             33        
                                                                 
Total params: 178,319
Trainable params: 178,319
Non-trainable params: 0
_________________________________________________________________


<div>
<img src="embeddin6.png" width="600" height="700"/>
</div>

In [71]:
# Embedding layer
1000*2

2000

In [72]:
# RNN layer
(2*32) + (32*32) + 32 # -> last 32 is bias

1120

In [73]:
# Dense layer
32 + 1  # -> 1 is bias

33

In [74]:
# Our vectorized labels
y_tr = np.asarray(y_train).astype('int32').reshape((-1,1))
y_te = np.asarray(y_test).astype('int32').reshape((-1,1))

In [75]:
y_tr.shape

(25000, 1)

In [76]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
history = model.fit(x_train,y_tr, validation_data=(x_test,y_te), epochs=10, verbose=2)

Epoch 1/10
782/782 - 14s - loss: 0.6012 - accuracy: 0.6585 - val_loss: 0.5570 - val_accuracy: 0.7093 - 14s/epoch - 18ms/step
Epoch 2/10
782/782 - 13s - loss: 0.4692 - accuracy: 0.7729 - val_loss: 0.5720 - val_accuracy: 0.7054 - 13s/epoch - 17ms/step
Epoch 3/10
782/782 - 13s - loss: 0.3918 - accuracy: 0.8198 - val_loss: 0.5852 - val_accuracy: 0.6854 - 13s/epoch - 16ms/step
Epoch 4/10
782/782 - 12s - loss: 0.3394 - accuracy: 0.8481 - val_loss: 0.6610 - val_accuracy: 0.6877 - 12s/epoch - 16ms/step
Epoch 5/10
782/782 - 12s - loss: 0.3021 - accuracy: 0.8655 - val_loss: 0.7265 - val_accuracy: 0.6774 - 12s/epoch - 15ms/step
Epoch 6/10
782/782 - 12s - loss: 0.2783 - accuracy: 0.8760 - val_loss: 0.8192 - val_accuracy: 0.6736 - 12s/epoch - 16ms/step
Epoch 7/10
782/782 - 12s - loss: 0.2574 - accuracy: 0.8851 - val_loss: 0.8181 - val_accuracy: 0.6678 - 12s/epoch - 15ms/step
Epoch 8/10
782/782 - 12s - loss: 0.2443 - accuracy: 0.8903 - val_loss: 0.9277 - val_accuracy: 0.6607 - 12s/epoch - 15ms/step


In [77]:
x_train[0].shape

(50,)

In [78]:
y_train[0].shape

()

In [79]:
x_test[0].shape

(50,)

In [80]:
y_test[0].shape

()

In [ ]:
# Create a Sequential model
model = Sequential()

# Add an Embedding layer
model.add(Embedding(input_dim=88583, output_dim=2, input_length=50))

# Add a SimpleRNN layer
model.add(SimpleRNN(64))

# Add a Dense layer for binary classification
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Print the model summary
model.summary()

# Train the model5
history = model.fit(x_train, y_tr, validation_data=(x_test, y_te), batch_size=24, epochs=5, verbose=2)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(x_test, y_test, verbose=0)
print(f'Test loss: {loss:.4f}')
print(f'Test accuracy: {accuracy:.4f}')

In [84]:

import numpy as np
from sklearn.metrics import accuracy_score, classification_report

# Predict on the test data
y_pred = model.predict(x_test)

# Convert predicted probabilities to class labels (e.g., for binary classification)
y_pred_class = (y_pred > 0.5).astype(np.int32)

# Print classification report (includes precision, recall, F1-score, etc.)
report = classification_report(y_test, y_pred_class)
print('Classification Report:\n', report)


# Calculate and print accuracy.

# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred_class)
print(f'Accuracy: {accuracy:.4f}')

782/782 [==============================] - 3s 4ms/step
Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.84      0.79     12500
           1       0.81      0.72      0.77     12500

    accuracy                           0.78     25000
   macro avg       0.78      0.78      0.78     25000
weighted avg       0.78      0.78      0.78     25000

Accuracy: 0.7786


In [86]:

text = ["the movie was good"]

# Load the tokenizer used during training
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text) 

# Tokenize the input text and convert it to an integer sequence
input_sequence = tokenizer.texts_to_sequences([text])

# Pad the sequence to match the input shape expected by the model
max_sequence_length = 50
input_sequence = pad_sequences(input_sequence, maxlen=max_sequence_length)

# Make the prediction
prediction = model.predict(input_sequence)

# Interpret the prediction (e.g., determine if it's positive or negative sentiment)
# In binary classification, we use a threshold to interpret the prediction
threshold = 0.5
sentiment_label = "positive" if prediction[0][0] > threshold else "negative"

print(f"Predicted sentiment: {sentiment_label}")


1/1 [==============================] - 0s 34ms/step
Predicted sentiment: positive


Fine-Tuning the Model:

Experiment with different model architectures and hyperparameters to find the best configuration for your task.
Adjust the number of layers and units in your neural network.
Explore more advanced techniques like bidirectional RNNs, LSTM, GRU, or pre-trained embeddings like Word2Vec or GloVe.